### ISSUE TITLE
Error when saving a favourite for the new relative periods

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/d2-analysis#12]
get this when saving a favorite for 2.27 with this PRs:
https://github.com/dhis2/pivot-tables-app/pull/71
https://github.com/dhis2/charts-app/pull/28
https://github.com/dhis2/event-reports-app/pull/4
https://github.com/dhis2/d2-analysis/pull/27

Oslo is reporting:
```
WestRegionAggregateItems.js:2479 Uncaught TypeError: Cannot read property 'setValue' of undefined
    at m.resetRelativePeriods (http://localhost:8081/app.js:30506:22)
    at m.clearDimension (http://localhost:8081/app.js:30439:21)
    at http://localhost:8081/app.js:31661:24
    at Array.forEach (native)
    at m.clearDimensions (http://localhost:8081/app.js:31660:30)
    at m.setUiState (http://localhost:8081/app.js:31542:20)
    at m.setState (http://localhost:8081/app.js:23817:30)
    at UiManager.t.setState (http://localhost:8081/app.js:21155:23)
    at InstanceManager.t.setState (http://localhost:8081/app.js:21861:22)
    at _fn (http://localhost:8081/app.js:22121:16)
```

**Comment by adrianq** [comment]
@tokland As the PRs are still open please create the PRs against the same branches so they get updated
